### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by aidinzolghadr** [charlesgriffiths/VoxelPerformance#1]
Hi,

Is it possible to detect collision on per-voxel basis?

Thanks

**Comment by charlesgriffiths** [comment]
Hi, thanks for reaching out. All voxel data is generated and kept on the graphics card, or in GPU-assigned RAM for an integrated GPU. Collision detection would mean either a) copying data to RAM where the CPU can access it, or b) writing a GPU based collision detection routine.

The package has an example of (a) and shows how to create unity terrain or mesh objects, but no collision. Is it possible, absolutely yes, but there's no attempt made in this package.
